export const DELETE_PRAYER_REQUEST = 'DELETE_PRAYER_REQUEST'
export const ALL_PRAYERS_REQUESTS_AVAILABLE = 'ALL_PRAYERS_REQUESTS_AVAILABLE'
export const EDIT_PRAYER_REQUEST = 'EDIT_PRAYER_REQUEST'
export const EDIT_USER_AVATAR = 'EDIT_USER_AVATAR'
